flaskr/flaskr/models.py
from sqlalchemy import Column, Integer, String
from sqlalchemy.sql.sqltypes import TIMESTAMP
from datetime import datetime
from database import Base


class Users(Base):
    __tablename__ = 'users'

    user_id = Column(Integer, primary_key=True)
    email = Column(String(50), unique=True)
    password = Column(String(50), unique=True)
    nickname = Column(String(50), unique=True)
    c_time = Column(TIMESTAMP, default=datetime.now)

    def __init__(self, id=None, email=None, password=None, nickname=None, c_time=None):
        self.id = id
        self.email = email
        self.password = password
        self.nickname = nickname
        self.c_time = c_time

    #def __repr__(self):
    #    return ''

flaskr/flaskr/__init__.py
from .flaskr import app

flaskr/flaskr/views/users.py
# -*- coding: utf-8 -*-
from flask import Flask, Blueprint, render_template, redirect, request,\
    url_for, session, flash
from models import Users
from database import db_session
from flask.ext.bcrypt import *
import re

app = Flask(__name__)
bcrypt = Bcrypt(app)
mod = Blueprint('users', __name__, url_prefix='/users',)


@mod.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        error = None
        email = request.form['email'].strip()
        nickname = request.form['nickname'].strip()
        password = request.form['password'].strip()
        password2 = request.form['password2'].strip()

        email = email.lower()

        if email == "" or nickname == "" or password == "" or password2 == "":
            error = 'Please input all the information'
        elif password2 != password:
            error = 'The password is not repeated correctly'
        elif len(password) < 6:
            error = 'The password has at least 6 characters'
        elif not re.match(r'^[0-9a-zA-Z_]{0,19}@' +
                          '[0-9a-zA-Z]{1,15}\.[com,cn,net]', email):
            error = 'Please input the right email'

        u = Users.query.filter(Users.email == email).first()
        if u is not None:
            error = 'The email has already exsit'

        if error is not None:
            return render_template('register.html', error=error)
        else:
            u = Users()
            u.email = email
            u.nickname = nickname
            u.password = bcrypt.generate_password_hash(password)
            db_session.add(u)
            db_session.commit()
            flash('Register Success!')
            return redirect(url_for('users.login'))

    return render_template('register.html')


@mod.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if session.get('logged_in'):
        return redirect(url_for('show_entries'))
    if request.method == 'POST':
        email = request.form['email'].strip()
        password = request.form['password'].strip()

        email = email.lower()

        u = Users.query.filter(Users.email == email).first()
        if u is None:
            error = "The user doesn\'t exsit.Please register first."
        elif bcrypt.check_password_hash(u.password, password):
            session['logged_in'] = True
            session['logged_email'] = email
            return redirect(url_for('show_entries'))
        else:
            error = "Your password is wrong.Try it again."

    return render_template('login.html', error=error)


@mod.route('/logout', methods=['GET', 'POST'])
def logout():
    session.pop('logged_in', None)
    flash('You were logged out')
    return redirect(url_for('users.login'))


@mod.route('/edit', methods=['GET', 'POST'])
def edit():
    u = Users.query.filter(Users.email == session['logged_email']).first()
    if request.method == 'POST':
        u.nickname = request.form['nickname']
        db_session.commit()
        flash('Edit Nickname Success!')
    return render_template('users/edit.html', u=u)


@mod.route('/editPsd', methods=['GET', 'POST'])
def editPsd():
    u = Users.query.filter(Users.email == session['logged_email']).first()
    error = None
    if request.method == 'POST':
        oldPassword = request.form['oldPassword'].strip()
        newPassword = request.form['newPassword'].strip()
        newPassword2 = request.form['newPassword2'].strip()
        if not bcrypt.check_password_hash(u.password, oldPassword):
            error = 'Your old password is not right.'
        elif newPassword != newPassword2:
            error = 'The password is not repeated correctly'
        elif len(newPassword) < 6:
            error = 'The password has at least 6 characters'
        else:
            u.password = bcrypt.generate_password_hash(newPassword)
            db_session.commit()
            flash('Edit Password Success!')
    return render_template('users/edit.html', u=u, error=error)

flaskr/flaskr/templates/layout.html
<!doctype html>
<title>Flaskr</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<div class=page>
  <h1><a href="{{ url_for('show_entries') }}">Flaskr</a></h1>
  <div class=metanav>
  {% if not session.logged_in %}
    <a href="{{ url_for('users.login') }}">log in</a>
  {% else %}
    <a href="{{ url_for('users.edit') }}">{{ session.logged_email }}</a>
    <a href="{{ url_for('users.logout') }}">log out</a>
  {% endif %}
  </div>
  {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  {% block body %}{% endblock %}
</div>

flaskr/flaskr/templates/login.html
{% extends "layout.html" %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('users.login') }}" method=post>
    <dl>
      <dt>Email:
      <dd><input type=text name=email>
      <dt>Password:
      <dd><input type=password name=password>
      <dd><input type=submit value=Login>
    </dl>
    <a href="{{ url_for('users.register') }}">Don't have account? Go to register</a>
  </form>
{% endblock %}

flaskr/flaskr/templates/register.html
{% extends "layout.html" %}
{% block body %}
  <h2>Register</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('users.register') }}" method=post>
    <dl>
      <dt>Email:
      <dd><input type=text name=email>
      <dt>Nickname:
      <dd><input type=text name=nickname>
      <dt>Password:
      <dd><input type=password name=password>
      <dt>Repeat Your Password:
      <dd><input type=password name=password2>
      <dd><input type=submit value=Register>
    </dl>
  </form>
{% endblock %}

flaskr/flaskr/templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
  {% if session.logged_in %}
    <form action="{{ url_for('add_entry') }}" method=post class=add-entry>
      <dl>
        <dt>Title:
        <dd><input type=text size=30 name=title>
        <dt>Text:
        <dd><textarea name=text rows=5 cols=40></textarea>
        <dd><input type=submit value=Share>
      </dl>
    </form>
  {% endif %}
  <ul class=entries>
  {% for entry in entries %}
    <li><h2>{{ entry.title }}</h2>{{ entry.text|safe }}
  {% else %}
    <li><em>Unbelievable.  No entries here so far</em>
  {% endfor %}
  </ul>
{% endblock %}

flaskr/flaskr/templates/users/edit.html
{% extends "layout.html" %}
{% block body %}
  <h2>Edit User Information</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('users.edit') }}" method=post>
    <dl>
      <dt>Email:
      <dd>{{u.email}}
      <dt>Nickname:
      <dd><input type=text name=nickname value={{u.nickname}}>
      <dd><input type=submit value=Edit>
    </dl>
  </form>
  <form action="{{ url_for('users.editPsd') }}" method=post>
    <dl>
      <dt>Old Password:
      <dd><input type=password name=oldPassword>
      <dt>New Password:
      <dd><input type=password name=newPassword>
      <dt>Repeat Your Password:
      <dd><input type=password name=newPassword2>
      <dd><input type=submit value=Edit>
    </dl>
  </form>
{% endblock %}